# Machine learning and statistics Assessment 2020


In [1]:
import scipy.stats
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency

### 1. Python function to calculate square root of 2 to 100 decimal places

Our assignment here is to write a python function, called sqrt2, that calculates and prints the square root of 2 to 100 decimal places. This has to be done without using any modules.
The square root of 2 is an irrational number, which means it cannot be written as a fraction and there will never be any pattern in the number.

First I tried the easiest method I could think of, which was:

In [2]:
def sqrt2practice():
    x = 2 ** 0.5
    print(x)
    
sqrt2practice()

1.4142135623730951


Unfortunately, Python only calculated 16 decimal places. This is because Python only stores an approximation of irrational numbers, so as to make it too heavy to calculate with. Let's try to get python to print out 100 decimals using the format() function.

In [3]:
def sqrt2practice2():
    x = 2 ** 0.5
    print("{:.100f}".format(x))
    
sqrt2practice2()

1.4142135623730951454746218587388284504413604736328125000000000000000000000000000000000000000000000000


Well, we got a bit further, 51 decimals this time. But then python is just showing us a bunch of zeros. 
We know that the square root of 2 is an irrational number, which never can be represented exactly by a finite number of digits,  so chances of this being correct are extremely small. Also, I checked what the correct value should be and I found this: 

1.41421356237309504880168872420969807856967187537694 80731766797379907324784621070388503875343276415727 
https://nerdparadise.com/math/reference/2sqrt10000 and https://apod.nasa.gov/htmltest/gifcity/sqrt2.1mil

So, it seems we haven't gotten much closer to what we are looking for. This simple formula is not going to do, time to really delve into the subject and find a solution.

#### Newton's Method

When trying to find a manual way of calculating the square root, I came across Newton's method.
Basically, what this method does, is take an original guess at the square root, and then with a simple formula, get closer and closer, until the difference between the last and the second last guess is adequately small.


In [4]:
# Return square root of 2, using Newton's approach  
def squareRoot() : 

    x = 2 # Initial guess 
    
    l = 0.000001 # Required difference between last and second last guess
    
    
    while True : # Keep going until condition becomes false
         
  
        root = 0.5 * (x + (2 / x)) # Get closer and closer to the correct number, by perfecting the initial guess, with this simple formula   

  
        if (abs(root - x) < l) : # If difference between root and x(last and second last guess) is smaller than l, break the loop. Use abs to convert negative int to positive
            break 
  
        x = root # last guess becomes root  
        
    s = format(root, ".100f") # Show 100 decimals
        
    return s 
  

    print(squareRoot())

    # Adapted from: https://www.geeksforgeeks.org/find-root-of-a-number-using-newtons-method/

In [5]:
squareRoot()

'1.4142135623730949234300169337075203657150268554687500000000000000000000000000000000000000000000000000'

Newton's method works, but still, Python won't calculate the square root of 2 to 100 digits.

After spending hours trying to figure out a way, I found something promising on stackoverflow. What if we try to find the square root of 2 * 10 * 200 (to leave 101 digits), and then format it in a way that gets rid of the superfluous zero's at the end and displays it in the right way? Got some inspiration here: https://stackoverflow.com/questions/64278117/is-there-a-way-to-create-more-decimal-points-on-python-without-importing-a-libra and here:
https://stackoverflow.com/questions/5187664/generating-digits-of-square-root-of-2

In [6]:
# code adapted from https://stackoverflow.com/questions/5187664/generating-digits-of-square-root-of-2

def sqrt2(): # Function that calculates the squareroot of 2, to a total of 100 digits. Keeping numbers as integers.
    
    a = 2 * (10**(2*100)) # to calculate 
    
    x_prev = 0 # Set initial guess at 0
    
    x_next = 1 * (10**100)
    
    while x_prev != x_next: # Keep going until x_prev == x_next
        
        x_prev = x_next # previous x is replaced by next x
        
        x_next = (x_prev + (a // x_prev)) >> 1 # Use a method like Newtons to get closer and closer to the correct number
        
    sqrt2=str(x_next) # Change x_next into a string so it can be used into format properly
    
    print('{}.{}'.format(sqrt2[:1], sqrt2[1:101])) # Format so the first digit comes before the '.' and the next 100 digits come after.




In [7]:
sqrt2()

1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727


Now, lets compare this value to the number found on Nerdparadise, as well as on the official NASA website:

1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727

It looks like we finally got to where we wanted to be!

### 2. Chi-squared test

A Chi-squared test tells us if there is a statistically significant difference between the expected frequencies and the observed frequencies in one or more categories of a contingency table. https://en.wikipedia.org/wiki/Chi-squared_test 

First, I need to create a Pandas DataFrame from the table, so I can perform the Chi-squared test on it. I got some help on how to create a DataFrame and how to rename the rows here:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [8]:
df = pd.DataFrame(np.array([[90, 60, 104, 95], [30, 50, 51, 20], [30, 40, 45, 35]]), columns=["A", "B", "C", "D"])
df.rename(index={0: "White collar", 1: "Blue collar", 2: "No collar"})


A   B    C   D
White collar  90  60  104  95
Blue collar   30  50   51  20
No collar     30  40   45  35

In [9]:
chi2, p, dof, expected = chi2_contingency(df) # Learned how to do this here: https://stackoverflow.com/questions/43963606/python-pandas-chi-squared-test-of-independence

In [10]:
chi2 # Display Chi-squared value

24.5712028585826

In [11]:
p # Display the associated p-value

0.0004098425861096696

In [12]:
dof # display the degrees of freedom

6

In [13]:
expected # Display the expected values if neighbourhood of residence is independent of occupation.

array([[ 80.53846154,  80.53846154, 107.38461538,  80.53846154],
       [ 34.84615385,  34.84615385,  46.46153846,  34.84615385],
       [ 34.61538462,  34.61538462,  46.15384615,  34.61538462]])

With a p-value of 0.0004 it is extremely unlikely that random chance can explain the observed values.

## 3. Standard deviation (STDEV.P vs STDEV.S)

Microsoft Excel has two different ways of calculating the standard deviation of an array of numbers. What is the difference?

In [172]:
x = np.array([1,23,100]) # Take a simple array to clearly see what is going on

First, I will use Numpy to calculate the standard deviation of my array, without subtracting 1 from len. So this method is similar to STDEV.P function in Excel. I am not specifying any ddof (Delta Degrees of Freedom), so this is set to it's default 0. The formula numpy is using to calculate the standard deviation of x is now: *np.sqrt(np.sum((x - np.mean(x))**2)/len(x))*

In [173]:
np.sqrt(np.sum((x - np.mean(x))**2)/len(x))

42.444735310230826

The built in Numpy function np.std gives us the same result. From now on, I will be using this built-in function.

In [174]:
np.std(x)

42.444735310230826

Now, I will add 'ddof = 1'. By doing so, 1 will be subtracted from the number of elements and in doing so provides an unbiased estimator of the variance of the infinite population. https://numpy.org/doc/stable/reference/generated/numpy.std.html
This is similar to STDEV.S in Excel, and calculates an estimate of the whole population from the sample. The function STDEV.P calculates the standard deviation of the sample, which is the population, in case the sample is the entire population.


In [175]:
np.std(x, ddof = 1)

51.98397188877869

As can be seen, there is a significant difference between the two calculated standard deviations. Let's dive deeper into the matter and try to explain what is going on.

In [146]:
y = np.random.randint(1,1001,100) # Create an array with 100 values, from 0 to 99

In [147]:
y

array([  9, 262, 856, 996, 309, 212, 372, 369, 904, 838, 137, 321, 673,
       186, 331, 781, 618,  50, 395,  57, 471, 266, 753, 804, 683, 917,
       647, 962, 568, 904, 998, 138, 821, 753, 462, 429, 198, 216, 317,
       328, 861, 320, 793, 228, 383, 278, 285,   7, 617, 252,  94, 660,
       924, 937,  30, 408,  53, 836, 783, 433, 298, 478, 379, 413, 228,
        92, 164, 107, 511, 834,  64, 527, 958, 175, 204, 320, 308, 476,
       138,  97, 862, 854,  85, 196, 441,  35, 435, 790, 668, 794,  41,
       942, 709, 477, 928, 254, 522, 778, 725, 398])

In [148]:
ysample = np.random.choice(y,19, replace=False) # Take a sampe of 20 numbers from the population y, without replacement, so no value can be selected twice.

In [149]:
ysample

array([ 94,  30, 683, 821, 998, 804,  97, 266, 278, 618, 298, 408,  50,
       647, 435, 673, 138, 478, 861])

In [150]:
np.std(y) #EXPLAIN ALL OF THIS WITH COMMENTS!

296.8183949825213

In [151]:
np.std(ysample)

297.0725682444007

In [152]:
np.std(ysample, ddof=1) # Closer to standard deviation of population

305.2130499306234

Now, let's try this again, but for a bigger population and a bigger sample:

In [89]:
ybig = np.arange (1000)

In [98]:
ybigsample = np.random.choice(ybig,199, replace=False)

In [99]:
ybigsample

array([990, 887, 951, 309, 632, 690, 672, 903, 976,  63, 222,  16,  48,
       133, 925, 158,  20, 880, 339, 119, 791, 298, 702, 577, 857, 547,
       206, 144, 652, 931, 735, 736,  78,  17, 301, 850, 442, 643, 590,
       786, 358, 594, 476,  21, 231, 149,   1,  71, 845, 708, 417, 273,
       286, 464, 827, 233, 607, 262, 193,  82, 132, 295, 835, 947, 987,
       944,  69, 641, 131, 347, 848,  66, 498, 881, 691, 608, 722, 431,
       388, 839,  35, 424, 215, 661, 993, 485,   7, 716, 465,  15, 393,
       159, 514, 237, 649, 637, 156, 596, 107, 693, 884,  52, 611, 169,
       787, 307, 764, 112, 121, 219, 333, 988, 731, 684, 694, 804, 369,
       185, 682, 907, 356,  42, 843, 869, 430, 192, 745, 103, 399, 743,
       950, 718, 154, 416, 604, 428, 554, 279, 603, 501, 208, 338, 143,
       678, 618, 788,  56, 755, 687, 715, 381, 639, 360, 630, 870, 197,
       836, 737, 101, 466, 408, 186, 849, 106, 904, 963, 833, 533, 528,
       230, 974, 204, 310, 195, 855,  53, 253, 710,  37, 965, 49

In [100]:
np.std(ybig)

288.6749902572095

In [101]:
np.std(ybigsample)

302.2486914914526

In [102]:
np.std(ybigsample, ddof = 1)

303.0109844839509

Again, Excel's STDEV.S method (equivalent to adding the ddof = 1), g

The reason STDEV.S (or adding ddof = 1 in numpy) is better at estimating the standard deviation of a population, when performed on a sample, is because division by *len(x)* can lead to an underestimate of the variance. https://stackoverflow.com/questions/27600207/why-does-numpy-std-give-a-different-result-to-matlab-std

To get rid of this bias (or at least part of it) we lower the number we divide by (degrees of freedom) to some number less than *len(x)*. The ddof value specifies how much you want to subtract from *len(x)*. Typically, a value of ddof = 1 is used, and this is identical to what Excel does in it's STDEV.S function.
The method of using *len(x)-1* works well in small and large samples alike, because the larger the sample, the closer the sample's variance will match the population's variance, and less compensation is needed. https://www.khanacademy.org/math/ap-statistics/summarizing-quantitative-data-ap/more-standard-deviation/v/review-and-intuition-why-we-divide-by-n-1-for-the-unbiased-sample-variance

SHOW WHY STDEV.S IS BETTER FOR A SAMPLE!! And shortly why -1 https://www.khanacademy.org/math/ap-statistics/summarizing-quantitative-data-ap/more-standard-deviation/v/review-and-intuition-why-we-divide-by-n-1-for-the-unbiased-sample-variance

### Show for a small population with small sample, medium with medium and large with large, to show effectiveness and scalability of -1 in STDEV.S 


o add a little more context, in the calculation of the variance (of which the standard deviation is the square root) we typically divide by the number of values we have.

But if we select a random sample of N elements from a larger distribution and calculate the variance, division by N can lead to an underestimate of the actual variance. To fix this, we can lower the number we divide by (the degrees of freedom) to a number less than N (usually N-1). The ddof parameter allows us to change the divisor by the amount we specify.

Unless told otherwise, NumPy will calculate the biased estimator for the variance (ddof=0, dividing by N). This is what you want if you are working with the entire distribution (and not a subset of values which have been randomly picked from a larger distribution). If the ddof parameter is given, NumPy divides by N - ddof instead. https://stackoverflow.com/questions/27600207/why-does-numpy-std-give-a-different-result-to-matlab-std

dividing by N-1 gets rid of some of the bias in the standard deviation. This gets rid of some of (but probably not all of) of the bias in the standard deviation. This is likely to be what you want if you're using the function on a random sample of a larger distribution. 